# Generated by Django 5.0.6 on 2024-06-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_post_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=255)),
            ],
        ),
    ]
