# Generated by Django 5.0.6 on 2024-06-02 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="members",
            name="role",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                to="articles.role",
            ),
        ),
    ]
